# 服务器端口
server:
  port: 8080

# 数据库
spring:
  datasource:
    url: jdbc:mysql://localhost::3306/?useSSL=false&amp;useUnicode=true&amp;allowMultiQueries=true&amp;characterEncoding=UTF-8
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver